name: expense_repositories
description: "The repositories that fetch data from network storage."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6



#  cupertino_icons: ^1.0.8
#  font_awesome_flutter: ^10.8.0
#  fl_chart: ^0.70.2
#  intl: ^0.20.2
#  flutter_colorpicker: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#
#  assets:
#    - assets/icons/
